apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - image: mysql:5.5
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    imagePullPolicy: IfNotPresent
    name: mysql
  restartPolicy: Always
